# Generated by Django 4.1.7 on 2023-04-10 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("candidate", "0002_vote"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vote", old_name="candidateName", new_name="selected_choice",
        ),
    ]
